Exception in thread tty:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vivek/Desktop/Apogee/Counselor_bot/Howie/howie-code/howie/frontends/tty.py", line 57, in go
    with open("client.txt", "rb") as client:
IOError: [Errno 2] No such file or directory: 'client.txt'

Traceback (most recent call last):
  File "../Howie/howie-code/runme.py", line 90, in <module>
    main()
  File "../Howie/howie-code/runme.py", line 86, in main
    time.sleep(10)
KeyboardInterrupt
Traceback (most recent call last):
  File "../Howie/howie-code/runme.py", line 90, in <module>
    main()
  File "../Howie/howie-code/runme.py", line 86, in main
    time.sleep(10)
KeyboardInterrupt
